#!/usr/bin/env node

const spawn = require('react-dev-utils/crossSpawn')
const pkg = require('./package.json')

let [command, ...args] = process.argv.slice(2)
const knownCommands = ['build', 'dev', 'export']

if (knownCommands.indexOf(command)<0) command = 'help'

const run = (...cmd) => spawn.sync('node', cmd, { stdio: 'inherit' })

let result = {}

if (command==='-v') {
  console.log(pkg.name, pkg.version)
} else if (command==='help') {
  console.log(`
  Usage
    $ react-builder <command> [options]

  Available Commands
    build     Build the application
    dev       Start the application in development mode
    export    Export the application as a static site
`)
} else if (command==='export') {
  // Build for production
  result = run(require.resolve('./scripts/build'))
  // Export
  if (!result.signal) {
    process.env.APP_EXPORT = 1
    result = run('build/server.js')
  }
} else {
  result = run(require.resolve('./scripts/' + command))
}

process.exit(
  result.signal ? 1 : result.status
)
