#!/usr/bin/env node

const path = require('path')
const fs = require('fs')

// Check that app has node_modules installed
if (!fs.existsSync(path.join(process.cwd(), 'node_modules'))) {
  console.log('Please run `npm install` or `yarn`')
  process.exit()
}

const spawn = require('react-dev-utils/crossSpawn')

let [command, ...args] = process.argv.slice(2)

if (command==='-v') {

  const pkg = require('./package.json')

  console.log(pkg.name, pkg.version)
  process.exit()
}

const knownCommands = ['build', 'dev', 'export']

if (knownCommands.indexOf(command) < 0) command = 'help'

const run = (...cmd) => spawn.sync('node', cmd, { stdio: 'inherit' })

let result = {}

switch (command) {
case 'help':
  console.log(`
  Usage
    $ react-builder <command> [options]

  Available Commands
    build     Build the application
    dev       Start the application in development mode
    export    Export the application as a static site
`)
  break
case 'export':
  // Build for production
  result = run(require.resolve('./scripts/build'))
  // Export
  if (!result.signal) {
    process.env.APP_EXPORT = 1
    result = run('build/server.js')
  }

  break

default:
  result = run(require.resolve('./scripts/' + command))
}

process.exit(
  result.signal ? 1 : result.status
)
